name: Publish

on:
  release:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/npm@master
    - name: Publish
      run: npm publish --access public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
